#!/bin/sh
#
# A shell script to publish draft
#
# Usage: ./pub Filename
#
# (1) Copy Filename to ../_posts/YY-MM-DD-Filename
#     with "date:" field added
# (2) The file is commited to git with commit message of:
#     Published on [permalink]
# (3) The change is pushed to master branch
# (4) The draft file is removed from the git repository
# (5) Now just wait for jekyll at GitHub Pages to build
#

# Set URL of the top page
Site_URL=http://sekika.github.io

Filename=$1

# Permanent link in the pretty format
# Change here when using other permalink format
Permalink=$Site_URL`date -u +/%Y/%m/%d/``echo $Filename | sed -e 's/\..*$/\//'`

if [ -z $Filename ]; then
  echo "Usage: $0 Filename"
  echo "See comment in the source file $0"
  exit
fi

if [ -e $Filename ]; then
  if [ -r $Filname ]; then
    if [ -d ../_posts ]; then
      if [ -w ../_posts ]; then
        DestFile=`date -u +%Y-%m-%d-`$Filename
      else
        echo "Directory ../_posts is not writable"; exit
      fi
    else
      echo "Directory ../_posts does not exist"; exit
    fi
  else
    echo "$Filename is not readable"; exit
  fi
else
  echo "$Filename does not exist"; exit
fi

echo "Copying $Filename to ../_posts/$DestFile"
date="date: "`date -u +%Y-%m-%d" "%T`" +0000"
echo "Adding Front matter: $date"
awk '{print}/^title:/{X=NR}NR==X{print "DATEDATEDATE"}' $Filename | sed -e "s/DATEDATEDATE/$date/" > ../_posts/$DestFile
if [ `diff $Filename ../_posts/$DestFile | wc -l` -ne 2 ]; then
  echo "Something wrong. Stop. Check ../_posts/$DestFile"; exit
fi
echo "Committing to repository."
cd ../_posts || { echo "cd ../_posts failed. Stop."; exit; }
git add $DestFile || { echo "git add $DestFile at ../_posts failed. Stop."; exit; }
git commit -m "Published on "$Permalink || { echo "Commit at ../_posts failed. Stop."; exit; }
echo "Removing draft."
cd ../_drafts  || { echo "cd ../_drafts failed. Stop."; exit; }
git rm $Filename || { echo "git rm $Filename failed. Stop."; exit; }
git commit -m "Remove draft because it was published" || { echo "Commit failed. Stop."; exit; }
echo "Pushing to master repository."
git push origin master || { echo "Push failed. Stop."; exit; }
echo "Published successfully."
echo "Now wait for some time and check published post at $Site_URL"

